const laptopData = [
  {
    title: "MacBook Air M2",
    brand: "Apple",
    ram: "8GB",
    storage: "256GB SSD",
    description: "Lightweight laptop with Apple M2 chip and Retina display.",
    price: 999,
  },
  {
    title: "MacBook Pro 14",
    brand: "Apple",
    ram: "16GB",
    storage: "512GB SSD",
    description: "Powerful performance laptop with M3 chip.",
    price: 1999,
  },
  {
    title: "XPS 13",
    brand: "Dell",
    ram: "16GB",
    storage: "512GB SSD",
    description: "Compact ultrabook with InfinityEdge display.",
    price: 1299,
  },
  {
    title: "Inspiron 15",
    brand: "Dell",
    ram: "8GB",
    storage: "1TB HDD",
    description: "Affordable everyday use laptop.",
    price: 650,
  },
  {
    title: "HP Spectre x360",
    brand: "HP",
    ram: "16GB",
    storage: "1TB SSD",
    description: "Convertible laptop with touchscreen display.",
    price: 1499,
  },
  {
    title: "HP Pavilion 14",
    brand: "HP",
    ram: "8GB",
    storage: "512GB SSD",
    description: "Slim and stylish laptop for daily tasks.",
    price: 750,
  },
  {
    title: "ThinkPad X1 Carbon",
    brand: "Lenovo",
    ram: "16GB",
    storage: "1TB SSD",
    description: "Business-class lightweight durable laptop.",
    price: 1600,
  },
  {
    title: "IdeaPad 3",
    brand: "Lenovo",
    ram: "8GB",
    storage: "256GB SSD",
    description: "Budget-friendly laptop for students.",
    price: 500,
  },
  {
    title: "ROG Zephyrus G14",
    brand: "Asus",
    ram: "16GB",
    storage: "1TB SSD",
    description: "High-performance gaming laptop.",
    price: 1700,
  },
  {
    title: "VivoBook 15",
    brand: "Asus",
    ram: "8GB",
    storage: "512GB SSD",
    description: "Portable laptop with powerful features.",
    price: 700,
  },
  {
    title: "Swift 3",
    brand: "Acer",
    ram: "8GB",
    storage: "512GB SSD",
    description: "Thin and lightweight performance laptop.",
    price: 680,
  },
  {
    title: "Predator Helios 300",
    brand: "Acer",
    ram: "16GB",
    storage: "1TB SSD",
    description: "Gaming laptop with high refresh rate display.",
    price: 1500,
  },
  {
    title: "Surface Laptop 5",
    brand: "Microsoft",
    ram: "16GB",
    storage: "512GB SSD",
    description: "Premium design with touchscreen display.",
    price: 1400,
  },
  {
    title: "Surface Go 3",
    brand: "Microsoft",
    ram: "8GB",
    storage: "128GB SSD",
    description: "Compact 2-in-1 laptop for portability.",
    price: 600,
  },
  {
    title: "Galaxy Book 3",
    brand: "Samsung",
    ram: "16GB",
    storage: "512GB SSD",
    description: "Sleek design with AMOLED display.",
    price: 1350,
  },
  {
    title: "Blade 15",
    brand: "Razer",
    ram: "16GB",
    storage: "1TB SSD",
    description: "Premium gaming laptop with RTX graphics.",
    price: 2200,
  },
  {
    title: "Omen 16",
    brand: "HP",
    ram: "16GB",
    storage: "1TB SSD",
    description: "High-performance gaming laptop.",
    price: 1650,
  },
  {
    title: "Legion 5",
    brand: "Lenovo",
    ram: "16GB",
    storage: "512GB SSD",
    description: "Gaming laptop with powerful GPU.",
    price: 1400,
  },
  {
    title: "Aspire 5",
    brand: "Acer",
    ram: "8GB",
    storage: "1TB HDD",
    description: "Affordable laptop for home use.",
    price: 550,
  },
  {
    title: "Envy 13",
    brand: "HP",
    ram: "16GB",
    storage: "512GB SSD",
    description: "Premium ultrabook with sleek design.",
    price: 1200,
  },
  {
    title: "Latitude 7420",
    brand: "Dell",
    ram: "16GB",
    storage: "512GB SSD",
    description: "Business laptop with secure features.",
    price: 1500,
  },
  {
    title: "Chromebook Spin 713",
    brand: "Acer",
    ram: "8GB",
    storage: "256GB SSD",
    description: "Fast Chromebook with touchscreen.",
    price: 620,
  },
  {
    title: "Yoga Slim 7",
    brand: "Lenovo",
    ram: "16GB",
    storage: "1TB SSD",
    description: "Slim and powerful ultrabook.",
    price: 1300,
  },
  {
    title: "ZenBook 14",
    brand: "Asus",
    ram: "16GB",
    storage: "512GB SSD",
    description: "Ultra-slim laptop with long battery life.",
    price: 1250,
  },
  {
    title: "Nitro 5",
    brand: "Acer",
    ram: "16GB",
    storage: "512GB SSD",
    description: "Affordable gaming laptop.",
    price: 1100,
  },
  {
    title: "Victus 15",
    brand: "HP",
    ram: "8GB",
    storage: "512GB SSD",
    description: "Mid-range gaming and productivity laptop.",
    price: 900,
  },
  {
    title: "TUF Dash F15",
    brand: "Asus",
    ram: "16GB",
    storage: "1TB SSD",
    description: "Durable gaming laptop with high refresh rate.",
    price: 1450,
  },
  {
    title: "Gram 17",
    brand: "LG",
    ram: "16GB",
    storage: "1TB SSD",
    description: "Ultra-light 17-inch productivity laptop.",
    price: 1800,
  },
  {
    title: "Pavilion Gaming 15",
    brand: "HP",
    ram: "16GB",
    storage: "512GB SSD",
    description: "Entry-level gaming laptop.",
    price: 1000,
  },
  {
    title: "TravelMate P2",
    brand: "Acer",
    ram: "8GB",
    storage: "512GB SSD",
    description: "Business-focused affordable laptop.",
    price: 720,
  },
  {
    title: "EliteBook 840",
    brand: "HP",
    ram: "16GB",
    storage: "512GB SSD",
    description: "Enterprise-grade secure laptop.",
    price: 1550,
  },
  {
    title: "ProBook 450",
    brand: "HP",
    ram: "8GB",
    storage: "1TB HDD",
    description: "Reliable office work laptop.",
    price: 800,
  },
  {
    title: "Mi Notebook Pro",
    brand: "Xiaomi",
    ram: "16GB",
    storage: "512GB SSD",
    description: "Slim design with high performance.",
    price: 950,
  },
  {
    title: "MateBook D15",
    brand: "Huawei",
    ram: "8GB",
    storage: "512GB SSD",
    description: "Affordable productivity laptop.",
    price: 780,
  },
  {
    title: "Alienware m16",
    brand: "Dell",
    ram: "32GB",
    storage: "1TB SSD",
    description: "High-end gaming laptop with premium build.",
    price: 2500,
  },
];

module.exports = laptopData;
